### PR TITLE
Sound updates

### PR DESCRIPTION
**Pull request by pixmusix**
Removed Original Large Example and replaced with two simple examples.
No more visuals, just audio processing.

### CODE REVIEW

**Comment by pixmusix** [comment]
Hello. may I follow up on this commit?

Thanks :)

**Comment by SableRaf** [comment]
Hi @pixmusix. Thank you for your contribution and sorry for the delayed answer. Could you share more details about your motivation for these changes? Some more context would help with reviewing your commits.

**Comment by pixmusix** [comment]
No worries. :)

1. As of right now the [Allpass webpage](https://processing.org/reference/libraries/sound/AllPass.html) shows no examples at all.

2. The example originally used focused to much of visual animations and not on actually using the filter.
The new examples are short and relevant to audio processing.

**Comment by SableRaf** [comment]
Thanks @pixmusix for the clarification. Pinging @kevinstadler who maintains the sound library for a second look :)

**Comment by kevinstadler** [comment]
Whoops sorry for the delay, yes that is all looking good (and the new sound library version is out as well so this documentation can go live!)

**Pull request merged**
