### PR TITLE
Automatic Releases Workflow

### PR DESCRIPTION
**Pull request by Stefterv**
Added a workflow to be able to trigger the fetchReleases script and create a pull request on the repo.

This workflow can be triggered manually, and then we can decide if we want to automatically also update the `content/download/selected.json` or if that would have to be done manually

### CODE REVIEW

**Comment by Stefterv** [comment]
Seems like we need to setup a Personal Access Token instead as the defined Github token can only read the current repository

**Comment by Stefterv** [comment]
One thing I dislike about the current system is that we have duplicate data, the original repo maintains its own state for releases and the website is not dynamically updating based on that.

One other approach would be to remove the releases content from the repo altogether, download the data on every build. And make the `processing4` repo trigger a web hook on netlify.

**Comment by SableRaf** [comment]
> Seems like we need to setup a Personal Access Token instead as the defined Github token can only read the current repository

Which specific [repository permissions](https://docs.github.com/en/rest/authentication/permissions-required-for-fine-grained-personal-access-tokens?apiVersion=2022-11-28) does this token need?

**Comment by SableRaf** [comment]
> One thing I dislike about the current system is that we have duplicate data, the original repo maintains its own state for releases and the website is not dynamically updating based on that.

Agreed!

> One other approach would be to remove the releases content from this repo altogether, download the data on every build. And make the `processing4` repo trigger a web hook on netlify.

That sounds reasonable and would support our efforts to adopt a more pull-based data flow across the Processing infra.

**Pull request merged**
