### PR TITLE
Content update tutorials

### PR DESCRIPTION
**Pull request by digitalcoleman**
Fixes to images for higher quality and added alt text for all images. Numerous mdx file tweaks. No other code affected.

### CODE REVIEW

**Comment by REAS** [comment]
@runemadsen please have a look at this. this is a large pull request from @digitalcoleman for the tutorials, updates to the mdx files and many updated images. i'm confused about all of the other changes in this pull request with your name next to them and where those came from?

**Comment by digitalcoleman** [comment]
I am a bit worried that this pull request might need to go direct to the main branch since I did a re-base in July after a lot of changes - and I think this branch is too old? Just let me know where best to do the pull request and I am on it!

**Comment by runemadsen** [comment]
This is just wonderful @digitalcoleman! Thanks so much for the hard work. I brought the `content-updates` branch up to date with `main` on my local machine and did the merge there. I'll clean up the branches so it's less confusing next time. Thank you!

**Comment by runemadsen** [comment]
This has now been deployed! http://processing.org.s3-website-us-east-1.amazonaws.com/tutorials

**Pull request merged**
