### PR TITLE
Gatsby V4, optimizations, and progress on spanish translation

### LINKED ISSUE #317: Get optimizations from `translation-es` into main with ignored translations

### PR DESCRIPTION
**Pull request by runemadsen**
This PR turned into quite the upgrade for the code of the website. There should be no changes in design or content, but a number of improvements have been made:

- **Gatsby V4**. The website is now updated from Gatsby `3` to `4`, which should make the build process a lot faster and the local development experience nicer.
- **Node 16**. The website didn't have a stated Node version, but was running with Node `12` in the GitHub Actions. The repo now has a `.nvmrc` file stating the Node version, and the GitHub Actions have been upgraded to use same version: Node `16`. 
- **Updated packages**. I have updated most packages to their newest versions. Since Gatsby doesn't support ESM packages yet, I had to keep some packages one version below their newest, but there are no dependency issues and everything seems to work.
- **Better build process**. I optimized the way we generate nodes in the build process, so we don't generate duplicate content. I also changed the way we save the `name` field in every node to not include the `locale`, which makes the logic easier on many of the pages when it comes to translations.
- **New hooks**. I implemented two news hooks to be used for translated content: `useTranslations` and `useTranslationsWithEnglishBase`. They are both documented and used on some pages. As we get ready to publish the first real translation, they might be used even more.
- **Spanish translation files**. This PR also adds a bunch of files for the Spanish translation. I currently disabled the translation, so the files won't get used and the build process will not slow down. As we get closer to finishing the translation, it will be very easy to enable it again.
- **Fix libraries search**. The libraries search had a problem where categories would shuffle around. I fixed it while making a more friendly version of the `useFilteredArray` hook.
- **Fix build issue for examples**. There was a build issue where the site would sometimes fail when building. This was because the examples would sometimes mistakenly try to load the `png` file instead of the `json` file in the example folder, and this would lead to an error when trying to read the JSON. This has been fixed and the site should build now.

@SableRaf This is a rather large pull request, and I have tested it as much as I can. If you could give it a good look on your local computer, that would make me feel a lot better. Here are the steps for making it run:
- Make sure you're running Node 16. I use `nvm` for this.
- Delete your `node_modules` folder
- Run `npm install`
- Then run `npm run dev`

Let me know if you run into any issues!

This fixes #317

### CODE REVIEW

**Comment by SableRaf** [comment]
Thanks @runemadsen for the detailed instructions! I have tried your branch locally and everything seems to run fine as far as I can tell. Are there specific tests you would like me to run?

**Comment by runemadsen** [comment]
Great! As long as you have gone through all the major sections on the website (which I also did), and it looks good, I think we're good to go!

**Comment by SableRaf** [comment]
Hey @runemadsen

I found one thing that looks broken: images in the "Environment" part don't seem to load. This is the same in the English and Spanish versions. 

image

node version:  v16.17.0. 
Tested on:
- Chrome Version 105.0.5195.102 (Official Build) (arm64)
- Safari Version 15.6.1 (17613.3.9.1.16)

**Comment by runemadsen** [comment]
Thanks for this! I can't replicate it on my own machine. Can you try running `npm run clean` and then `npm run dev` to see if it fixes it? It might be a cache problem.

**Comment by SableRaf** [comment]
> Thanks for this! I can't replicate it on my own machine. Can you try running `npm run clean` and then `npm run dev` to see if it fixes it? It might be a cache problem.

That did it! 

I have another question: you wrote that the Spanish version is disabled but the menu does appear when I run the website locally and I can switch to Spanish with the incomplete translation. Is this content supposed to be hidden?

image

**Comment by runemadsen** [comment]
ok, great!

**Comment by SableRaf** [comment]
Thanks @runemadsen! I did a last test and everything looks good. Merged and will do a new release of the website today as there have been quite a few changes since last week :)

**Comment by runemadsen** [comment]
Excellent! Keep me posted on how it goes!

**Pull request merged**
