### PR TITLE
Keywords script

### PR DESCRIPTION
**Pull request by runemadsen**
This PR adds a script that generates the `keywords.txt` file needed for the Processing IDE syntax highlighting. I made sure to compare the output of the [new file](https://github.com/processing/processing-website/blob/keywords-script/scripts/keywords.txt) to the  [old file](https://github.com/processing/processing4/blob/master/java/keywords.txt) and the differences are minor:

- **Some entries are missing in the new file**. I believe most entries below are deprecated API entries, except the `keys()` functions that are still in the source code but not documented with JavaDoc:
  - `blendColor()`
  - `displayWidth`
  - `displayHeight`
  - `FloatDict.keys()`
  - `IntDict.keys()`
  - `PVector.get()`
  - `StringDict.keys()`. 

- **Some entries are added to the new file**. I also believe this is mostly because of API changes.
  - `circle()`
  - `FloatDict.maxIndex()`
  - `FloatDict.minIndex()`
  - `mask()`
  - `PImage.blendColor()`
  - `pop()`
  - `push()`
  - `setLocation()`
  - `setResizable()`
  - `setTitle()`
  - `square()`
  - `Table.matchRowIterator()`
  - `Table.sort()`
  - `XML.getChildCount()`
  - `XML.parse()`
  - `XML.setLong()`

- **Some entries were duplicated**. These entries were listed both in `keywords_base.txt` and in the auto-generated code. I removed all of them from the auto-generated code:
  - `HALF_PI`
  - `PI`
  - `QUARTER_PI`
  - `TAU`
  - `TWO_PI`
  - `PVector` (listed with both `FUNCTION1` and `KEYWORD5`. I kept it as `KEYWORD5`
  - `pixelHeight`

- **Smaller edits**. I made a few smaller edits to some entries:
  - `PShader.set()` was listed as `PShader`, which meant that there were two `PShader` entries. I changed it to `set` so it reflects what we do with other class methods.
  - `PFont.list()` was listed in the `FUNCTION1` category, but I changed it to be `FUNCTION2` like all the other class methods.

@REAS @benfry You can find the [new keywords.txt file here](https://github.com/processing/processing-website/blob/keywords-script/scripts/keywords.txt). Can you take a look and see whether it works for the PDE? If you have any feedback, just comment on this PR. Once we're ready to go, I can push a simple script to copy the file over if needed, so let's keep this PR open until then.

### CODE REVIEW

**Comment by REAS** [comment]
@runemadsen for the list that are duplicated, i think it would be better to remove them from `keywords_base.txt` and leave the generated versions. what do you think?

**Comment by runemadsen** [comment]
That sounds good to me! I basically just need to delete them from `keywords_base.txt` and everything should work.

**Comment by REAS** [comment]
ok, good. so you removed them "by hand" rather than a conditional in the code... i'll do this right now

**Comment by runemadsen** [comment]
Great! The script will automatically check if an entry is in the `keywords_base.txt` file before adding it to the newly generated `keywords.txt` file. So if you delete the following from the base file, they should be included as a part of the auto-generated code:

- `HALF_PI`
- `PI`
- `QUARTER_PI`
- `TAU`
- `TWO_PI`
- `PVector`
- `pixelHeight`

Let me know if that doesn't seem to be the case.

**Comment by REAS** [comment]
@runemadsen did you see and implement this in the script? 
```
# Suppressed from Generate to avoid conflicts with variables inside methods

width	KEYWORD4	width_
height	KEYWORD4	height_

ArrayList	FUNCTION1	ArrayList
HashMap	FUNCTION1	HashMap
```

**Comment by runemadsen** [comment]
I did make a list of things to ignore (based on how I presumed the Pearl script to work:

https://github.com/processing/processing-website/blob/keywords-script/scripts/createKeywords.js#L22-L26

So it will not include any `width`, `height`, `x`, `y`, and `z` variable. When I tested the output of the script, it was identical to the current keywords, so I think it behaves in the same way.

**Comment by REAS** [comment]
hey @runemadsen i think this is ready to merge now

**Comment by runemadsen** [comment]
Great!

@REAS @benfry What would you like to do as far as moving this file into the `processing4` repo? I can think of three things:

1. We just run the script and manually copy over the `keywords.txt` file to the correct place in the `processing4` repo.
2. I add a copy command to the script, so it happens automatically if the `processing4` repo is next to the `processing-website` repo on the local machine.
3. I upload it as a part of the website and the PDE can download it just like `reference.zip`

I'm open to any of those things, so let me know what you prefer and I'll push it to this branch and merge it.

**Comment by REAS** [comment]
I think #2 works well, thank you!

**Comment by runemadsen** [comment]
Okay, it is pushed! I moved the README docs to the main README and added a section on [how to run the script](https://github.com/processing/processing-website/tree/keywords-script#keywordstxt).

This should be good to go! This fixes #214

**Pull request merged**
