### PR TITLE
Generated files from updated build script (processing-doclet)

### PR DESCRIPTION
**Pull request by SableRaf**
These files were created by running the `processingrefBuild.sh` script as updated by Kevin in https://github.com/processing/processing-doclet/pull/5

### CODE REVIEW

**Comment by SableRaf** [comment]
@kevinstadler check out the [sound doc on the deploy preview](https://deploy-preview-516--java-processing-faf822.netlify.app/reference/libraries/sound/index.html). Is everything as it should be?

**Comment by SableRaf** [comment]
Thanks for the feedback @kevinstadler! 

I made [a branch](https://github.com/processing/processing-doclet/tree/bug-fixes-pr5-pr6
) on the processing-doclet repo to merge both your PRs and ran `./processingrefBuild.sh sound` on it so that it won't affect other libs.

Please check [the updated deploy test](https://deploy-preview-516--java-processing-faf822.netlify.app/reference/libraries/sound/index.html) and let me know how it looks.

**Comment by kevinstadler** [comment]
Yes looks good! I just published the new release to both the `latest` and the `v2.4.0` tag, so I guess it will be automatically drawn to the contribution manager tomorrow?

**Comment by SableRaf** [comment]
@kevinstadler Yes, Processing Sound 2.4.0 been correctly added to the contribution manager. Congratulations on the release 🎉 I have merged this PR and the updated documentation is live!

**Pull request merged**
