### PR TITLE
Set release tag from time and date

### PR DESCRIPTION
**Pull request by SableRaf**
Make a unique tag for workflow releases from the time and date.

### CODE REVIEW

**Comment by runemadsen** [comment]
Thanks for this! I think it's a good idea to automatically create the `version`. Can you delete the [`version` input](https://github.com/processing/processing-website/blob/SableRaf-ProcessingDeployAction-SetTagFromDateTime/.github/workflows/deploy.yml#L6-L9) from the action config file? Then, feel free to merge :)

**Comment by runemadsen** [comment]
Just saw your comment in Slack. What is the `version` attribute used for now?

**Comment by SableRaf** [comment]
> Just saw your comment in Slack. What is the `version` attribute used for now?

@runemadsen It is used to set the name of the release: `name: 'Website ${{ inputs.version }}'`

**Comment by SableRaf** [comment]
> Thanks for this! I think it's a good idea to automatically create the `version`. Can you delete the [`version` input](https://github.com/processing/processing-website/blob/SableRaf-ProcessingDeployAction-SetTagFromDateTime/.github/workflows/deploy.yml#L6-L9) from the action config file? Then, feel free to merge :)

Right now I'm automatically creating the unique tag, not the version name. I'm actually not sure where the idea of having a unique tag for each release started or if it is necessary but I emulated it here.

Automatically generating the version name would be tricky, since we may want to get the website of Beta or bump up from version 7 to 8 at some point and this is subjective and not a decision we can easily automate.

**Comment by runemadsen** [comment]
Thanks for that. The unique tag is only needed for the GitHub release, since GitHub uses this to make a Git tag in the current HEAD of the branch. I was just wondering whether we need the `version` at all if it's only used to populate the release field. Could we just rename it to `Release title`?

**Comment by SableRaf** [comment]
> I was just wondering whether we need the `version` at all if it's only used to populate the release field. Could we just rename it to `Release title`?

@runemadsen: Gotcha! I made this change. Do these commit look ok? I'm kinda new to the whole GH workflows thing :)

**Comment by runemadsen** [comment]
Looks good to me! I've never set an ENV variable like this, but give it a whirl and see how it goes!

**Comment by SableRaf** [comment]
Hmm, yeah that doesn't seem to be [the proper way to set env variables](https://docs.github.com/en/actions/learn-github-actions/variables#defining-environment-variables-for-a-single-workflow). I'll fix this before merging.

**Comment by SableRaf** [comment]
@runemadsen It worked! Here's what I ended up with:

```
- name: Set Tag Name
        run: |
          echo "RELEASE_DATE=$(date '+%Y-%m-%d-%H%M%S')" >> ${GITHUB_ENV}
```

**Comment by runemadsen** [comment]
Great!

**Pull request merged**
