### PR TITLE
New logos

### PR DESCRIPTION
**Pull request by bravomartin**
Adds logos for Processing Pyton and Processing Android, and changes p5 logo to the original one.

### CODE REVIEW

**Comment by bravomartin** [comment]
image

**Review by runemadsen — CHANGES_REQUESTED** [review]
Very nice! Two small things:

I'm getting a warning from CSS classes that are used but not defined:

```
warn ./src/components/Topbar.js
Attempted import error: 'android' is not exported from './Topbar.module.css' (imported as 'css').
warn ./src/components/Topbar.js
Attempted import error: 'python' is not exported from './Topbar.module.css' (imported as 'css').
```

Can we change the highlight colors of Android and Python to the medium colors instead of the dark ones? That's what we do for the other logos.

**Comment by bravomartin** [comment]
fixed the issues. Re. the colors I was just following what dana did. I changed them but I'm not convinced with the look.

It was taking a lot of width, so I made the two-word ones into two lines. Not fully sold on that either. Thoughts?

image

**Comment by runemadsen** [comment]
I actually think this is very nice! Let's get it in and then tweak if needed.

**Pull request merged**
