### PR TITLE
Solved > warning:Invalid prop 'fluid' supplied to 'Image'

### PR DESCRIPTION
**Pull request by smrnjeet222**
* removed unused imports
* hovered state was unused
* added `GatsbyImageSharpFluid` to remove warning: ` Failed prop type: Invalid prop fluid supplied to Image`

### CODE REVIEW

**Review by smrnjeet222 — COMMENTED** [review]
resolved conflict w/ PR#85

**Comment by runemadsen** [comment]
Thanks so much for this @smrnjeet222! I just saw your message on Twitter. Are you interested in contributing more to this repo? If so, I'm sure we can find stuff that needs to be done on the new website before we can launch it :)

**Comment by smrnjeet222** [comment]
Yes I'm interested in contributing to this project

**Comment by runemadsen** [comment]
Amazing! Let me just talk with the team tomorrow and get back to you :)

**Pull request merged**
