### PR TITLE
Sound updates

### PR DESCRIPTION
**Pull request by kevinstadler**
AllPass examples ready to merge into main!

### CODE REVIEW

**Comment by kevinstadler** [comment]
None of the AllPass documentation (not even the basic method documents) are showing up in the netlify-preview, not sure why (they look fine on the currently live website: https://processing.org/reference/libraries/sound/index.html)

**Comment by Stefterv** [comment]
Probably because this branch is somewhat behind on main

**Comment by SableRaf** [comment]
Looking good to me now @kevinstadler. Just say the word and I'll merge :)

**Comment by kevinstadler** [comment]
The Spirit helps me! I have it now, intact.

And firmly write: ‘In the Beginning was the Act!’

**Comment by SableRaf** [comment]
@kevinstadler Hahaha! Perfect ⚡️👻

**Pull request merged**
